kind: PersistentVolume
apiVersion: v1
metadata:
  name: siddhi-pv
  labels:
    type: local
spec:
  storageClassName: standard
  persistentVolumeReclaimPolicy: Recycle
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/siddhi_user/"
  # For NFS in GKE use the following block
  # nfs:
  #   server: <SERVER_IP>
  #   path: <PATH>
